### ISSUE TITLE
Referenced before assignment

### ISSUE THREAD

**Issue by cmdrrobin** [xirixiz/afvaldienst#1]
I can across the following message when using the Afvalwijzer in Home Assistant:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    afvaldienst = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 43, in __init__
    self._jsonData = self.__get_data_json()
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 55, in __get_data_json
    jsonData = (jsonResponse['data']['ophaaldagen']['data'] + jsonResponse['data']['ophaaldagenNext']['data'])
UnboundLocalError: local variable 'jsonResponse' referenced before assignment
```

**Comment by xirixiz** [comment]
True, no data is available from mijnafvalwijzer.nl, hence the error. Just implemented better error handling.
You can check the url manually wheteher data is available (replace X) : https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=XXXXXX&street=&huisnummer=X&toevoeging=&langs=nl
